  version: "3"
  services:
    postgresdb:
      image: postgres:9.6
      container_name: factorydb_dkr
      ports:
        - 5432:5432
      env_file:
        - .db.env
    application:
      container_name: fc_application
      image: fc_application
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
         - 8080:8080
      env_file:
        - .app.env
      depends_on:
         - postgresdb